source 'http://rubygems.org'

gem 'cucumber'
gem 'rspec'
gem 'rake'
gem 'chromedriver-helper'
gem 'httparty'
gem 'json'
gem 'faker'
gem 'cpf_faker'
gem 'site_prism'
gem 'pry-byebug'
gem 'selenium-webdriver'
gem 'gherkin'